-- Dev/demo parts catalog. Names are deliberately generic (what a tech would
-- actually say they used), not manufacturer SKUs.
INSERT INTO parts_catalog (category, name, unit) VALUES
  ('Electrical', 'Circuit Breaker - 15A', 'each'),
  ('Electrical', 'Circuit Breaker - 20A', 'each'),
  ('Electrical', 'Circuit Breaker - 30A', 'each'),
  ('Electrical', 'Wire Nuts', 'box'),
  ('Electrical', 'Outlet', 'each'),
  ('Electrical', 'GFCI Outlet', 'each'),
  ('Electrical', 'Light Switch', 'each'),
  ('Electrical', 'Electrical Tape', 'roll'),
  ('Electrical', 'Romex Wire 12/2', 'ft'),
  ('Electrical', 'Romex Wire 14/2', 'ft'),
  ('Electrical', 'Junction Box', 'each'),
  ('Electrical', 'Conduit', 'ft'),
  ('Plumbing', 'PVC Pipe - 1/2 in', 'ft'),
  ('Plumbing', 'PVC Pipe - 3/4 in', 'ft'),
  ('Plumbing', 'Pipe Fitting - Elbow', 'each'),
  ('Plumbing', 'Pipe Fitting - Coupling', 'each'),
  ('Plumbing', 'Shut-off Valve', 'each'),
  ('Plumbing', 'Pipe Sealant', 'each'),
  ('Plumbing', 'Drain Trap', 'each'),
  ('Plumbing', 'Faucet', 'each'),
  ('Plumbing', 'Supply Line', 'each'),
  ('HVAC', 'Air Filter', 'each'),
  ('HVAC', 'Refrigerant', 'lb'),
  ('HVAC', 'Thermostat', 'each'),
  ('HVAC', 'Duct Tape', 'roll'),
  ('HVAC', 'Capacitor', 'each'),
  ('HVAC', 'Contactor', 'each'),
  ('HVAC', 'Condensate Pump', 'each'),
  ('Fasteners & Hardware', 'Screws - Wood', 'box'),
  ('Fasteners & Hardware', 'Screws - Sheet Metal', 'box'),
  ('Fasteners & Hardware', 'Bolts', 'box'),
  ('Fasteners & Hardware', 'Wall Anchors', 'box'),
  ('Fasteners & Hardware', 'Zip Ties', 'pack'),
  ('Fasteners & Hardware', 'Mounting Bracket', 'each'),
  ('General Supplies', 'Caulk', 'tube'),
  ('General Supplies', 'Silicone Sealant', 'tube'),
  ('General Supplies', 'Shop Rags', 'pack'),
  ('General Supplies', 'Safety Gloves', 'pair');
